### ISSUE TITLE
prijevod-NezadovoljniOdgovorom-1 (reported by MeliSkeli)

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati-theme#123]
**Describe the bug**

Podstranica ‘Pomoć’
Naslov: Nezadovoljni ste dobivenim odgovorom na — Statistika antigenskih testiranja COVID-19?
1. pitanje ‘Ako niste dobili odgovor u roku 15 dana možete’ 
Promijeniti prijevode ponuđenih odgovora: 
a) “Poslati odgovor tijelu javne vlasti kojim ih požurujete da odgovore (...)”
b) “ U roku 15 dana od dana istjeka roka za odgovor (...)”

**To Reproduce**
Go to: https://imamopravoznati.org/help/unhappy/statistika_antigenskih_testiranj
Click on: prvo pitanje ‘Ako niste dobili odgovor u roku 15 dana možete’
Scroll down to ‘.....’
See error: ponuđeni odgovori:
a) “Poslati odgovor tijelu javne vlasti kojim ih požurujete da odgovore (...)” - poslati požurnicu
b) “ U roku 15 dana od dana istjeka roka za odgovor (...)” - 15 dana od dana istjeka roka bi bilo 30 dana. 

**Expected behavior**

Promijeniti ponuđene odgovore:
a) Poslati požurnicu tijelu javne vlasti kojom tražite da odgovore što prije (...) (umjeto: “Poslati odgovor tijelu javne vlasti kojim ih požurujete da odgovore (...)” 
b) Ako tijelo nije tražilo produljenje roka za odgovor (...) (umjesto U roku 15 dana od dana istjeka roka za odgovor (...))

**Screenshots**

![Screenshot from 2021-08-27 21-49-07](https://user-images.githubusercontent.com/1014134/131181261-60030895-537c-4267-ae43-fc52fc790b97.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Smartphone (please complete the following information):**

**Additional context**

Internal doc: https://docs.google.com/document/d/1MaTtGt_0m9uub5p1JU3GxkpZIfu07Q1WOSNyoJvKj5c/edit

**Comment by MelisaS** [comment]
Hej @schlos  
1. Požurnica: oke mi je da ostane ista formulacija oko požurnice ako tako mora biti, djelovalo mi je kao gomilanje riječi, ali očigledno postoji razlog zašto tako treba biti.
2. Rok za žalbu: da, nespretno sam to sročila. Puna rečenica bi bila:
**Po isteku roka od 15 dana ako tijelo nije ništa odgovorilo možete poslati žalbu Povjereniku za informiranje.** (umjesto: U roku 15 dana od dana istjeka roka za odgovor možete poslati žalbu Povjereniku za informiranje. Ovako sročeno ispada da moraš čekati mjesec dana da bi se mogao žaliti jer ti tijelo nije ništa odgovorilo.)

**Comment by schlos** [comment]
fixed
