### ISSUE TITLE
RTI day banner

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati-theme#37]
### Steps to reproduce

lib/views/general/_popup_banner.html.erb
### Expected behavior

```
It's International Right To Know Day. Do your friends know they have a right to information? <strong>Let them know.</strong> Share on <a href="https://www.facebook.com/sharer/sharer.php?u=https%3A//www.whatdotheyknow.com/">Facebook</a> or <a href="https://twitter.com/home?status=You%20have%20the%20right%20to%20access%20information%20held%20by%20public%20authorities.%20By%20law,%20they%20have%20to%20respond%20www.whatdotheyknow.com%20%23RightToKnowDay%20">Twitter</a>.
```

**Comment by schlos** [comment]
@MeliSkeli,
prijedlog je da pripremimo za dan prava na pristup infromacijama neki banner, po uzoru na WhatDoTheyKnow, npr.:

> It's International Right To Know Day. Do your friends know they have a right to information? Let them know. + Link to share na Twitter.

Hoces li mi poslati kratku recenicu kao pripremu za RTI day?

**Comment by MelisaS** [comment]
@schlos evo je:

Međunarodni je dan prava na pristup informacijama. Znaju li vaši prijatelji da imaju pravo znati i ono što im vlasti žele sakriti? Javite im to.

**Comment by schlos** [comment]
Title: **28. rujna je Međunarodni dan prava na pristup informacijama**
Content:
`Znaju li vaši prijatelji da imaju pravo znati i ono što im vlasti žele sakriti? <strong>Javite im to.</strong> Podijelite na <a href="https://www.facebook.com/sharer/sharer.php?u=https%3A//imamopravoznati.org/" target="_blank">Facebooku</a>, <a href="https://twitter.com/intent/tweet?url=https://imamopravoznati.org&text=Imate%20pravo%20na%20pristup%20informacijama,%20dokumentima,%20ugovorima%20od%20tijela%20javne%20vlasti.%20Po%20zakonu,%20moraju%20odgovoriti%20-%20zatra%C5%BEi%20putem" target="_blank">Twitteru</a> ili <a href="https://www.linkedin.com/shareArticle?mini=true&url=https://imamopravoznati.org" target="_blank">LinkedInu</a>.`
