### ISSUE TITLE
Fix translation on homepage 'tijelima javne vlasti'

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati-theme#43]
### Actual behavior

> Od koga mogu tražiti informacije?
> 
> Imamo pravo znati obuhvaća zahtjeve prema 5.868 tijelima javne vlasti, uključujući:

Screenshot: https://qsnapnet.com/snaps/opril0p6s3k

### Steps to reproduce

Go to homepage

### Expected behavior

Imamo pravo znati obuhvaća zahtjeve prema 5.868 **tijela** javne vlasti, uključujući

**Comment by LanaPdg** [comment]
Možeš provjeriti što si mislio ovdje? Meni izgleda točno na webu (tijela javne vlasti)

**Comment by schlos** [comment]
Ispravljeno je u medjuvremenu s novim prijevodima.
