### ISSUE TITLE
Fix translation in feedback form 'dobio/la sam'

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati-theme#49]
### Actual behavior

> dobio/la sam

> Please tell us more (this one is already reported in core https://github.com/codeforcroatia/alaveteli/issues/10)

### Steps to reproduce

![media-20161012](https://cloud.githubusercontent.com/assets/1014134/20038827/ac12cf00-a46c-11e6-8a7a-341abf4d08cf.png)

### Expected behavior

u neutralnom rodu izvesti recenicu

**Comment by LanaPdg** [comment]
Edited; Pojavila se poruka o pogrešci

**Comment by schlos** [comment]
Ceka da se uploda nova verzija prijevoda na portal.

**Comment by schlos** [comment]
Izmjene uplodane na web @LanaPdg hoces lu provjeriti je li sada dobro?

Nove ispravke mozes raditi putem Transifexa:
https://www.transifex.com/code-for-croatia/imamo-pravo-znati/theme-v03300po/
