### ISSUE TITLE
Fix display of names - remove 's

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati-theme#54]
### Actual behavior

FirstName LastName's

### Steps to reproduce

![media-20160808](https://cloud.githubusercontent.com/assets/1014134/20039064/83bbcd14-a470-11e6-8cce-cc3faf2288ed.png)

### Expected behavior

FirstName LastName

**Comment by LanaPdg** [comment]
Ispravljeno na Transifexu

**Comment by schlos** [comment]
Jos nije ispravljeno: https://qsnapnet.com/snaps/j7kfziuadjm
URL: http://imamopravoznati.org/user/katarina/wall

**Comment by schlos** [comment]
Izmjene uplodane na web i ispravjeno!
