### ISSUE TITLE
Fix translation in email 'posalji pratecu poruku'

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati-theme#59]
### Actual behavior

![media-20151205](https://cloud.githubusercontent.com/assets/1014134/20039217/d53eff24-a472-11e6-8655-eaa967297364.png)

**Comment by schlos** [comment]
@LanaPdg please check if this string is available in Transifex? If not, reassign back to me with comment.

**Comment by LanaPdg** [comment]
@schlos now we have only - {{user_name}} je poslao/la dodatnu poruku prema {{public_body}} 
[#1376]

**Comment by schlos** [comment]
Waiting for next language upload to Live.

**Comment by schlos** [comment]
Izmjene uplodane na web @LanaPdg hoces lu provjeriti je li sada dobro?

Nove ispravke mozes raditi putem Transifexa:
https://www.transifex.com/code-for-croatia/imamo-pravo-znati/

**Comment by schlos** [comment]
Looks fine now. New text is:

```
---------------------------------------------------------------------
Administrator Miroslav je koristio/la Imamo pravo znati da Vam pošalje poruku ispod.
Vaši detalji, uključujući Vašu adresu e-pošte, neće biti nikome dostupni.
Ako odgovorite na ovu poruku, otići će izravno na Administrator Miroslav te će tako saznati vašu e-mail adresu. Odgovorite samo ako ste s tim suglasni.
---------------------------------------------------------------------
```
