### ISSUE TITLE
Prijevod 'sveukupno'

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati-theme#69]
### Steps to reproduce

![unnamed](https://user-images.githubusercontent.com/1014134/54488393-8f24d100-48a1-11e9-8188-63841d3b1a95.png)

**Comment by LanaPdg** [comment]
@schlos - changed to status

**Comment by schlos** [comment]
Waiting for next language upload to Live.

**Comment by schlos** [comment]
Izmjene uplodane na web @LanaPdg hoces lu provjeriti je li sada dobro?

Nove ispravke mozes raditi putem Transifexa:
https://www.transifex.com/code-for-croatia/imamo-pravo-znati/
