### ISSUE TITLE
Prijevod 'Žao nam je ali samo IME PREZIME može raditi to.'

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati-theme#70]
### Actual behavior

Žao nam je ali samo IME PREZIME može raditi to.

### Steps to reproduce

1. Ulogiraj se na imamopravoznati.org
2. Klikni na link http://imamopravoznati.org/request/6683/response/8331#followup

![unnamed (1)](https://user-images.githubusercontent.com/1014134/54488772-373c9900-48a6-11e9-8c35-6e5698893d06.png)

### Expected behavior

Prijevod treba prilagoditi situaciji - popraviti sintaksu.

**Comment by LanaPdg** [comment]
changed to; Žao nam je ali samo {{user_name}} može to učiniti.

[#781]

**Comment by schlos** [comment]
Waiting for next language upload to Live.

**Comment by schlos** [comment]
Izmjene uplodane na web @LanaPdg hoces lu provjeriti je li sada dobro?

Nove ispravke mozes raditi putem Transifexa:
https://www.transifex.com/code-for-croatia/imamo-pravo-znati/
