### ISSUE TITLE
Objava obrazaca za predstavke

### ISSUE THREAD

**Issue by MeliSkeli** [codeforcroatia/imamopravoznati-theme#75]
### Actual behavior
Trenutno u rubrici pomoć imamo opisano kako poslati zahtjev https://imamopravoznati.org/help/requesting, ili nakon ažuriranja statusa opisno predlaže daljnje korake

### Steps to reproduce
Kako korisnici mahom nisu pravnici dodavanje obrazaca objavljenih na stranici PristupInfo https://www.pristupinfo.hr/pravni-okvir/upute-smjernice-obrasci/ (na stranici niže link na obrasce pod naslovom Preuzimanje obrazaca) pomoglo bi im da u dokument uključe sve nužne elemente

### Expected behavior
Obrasci se mogu postaviti na podstranicu Pomoć i ako je moguće kod ažuriranja statusa ponuditi odgovarajući obrazac

**Comment by MeliSkeli** [comment]
Opisano detaljno pod naslovom "Obrasci"

**Comment by MeliSkeli** [comment]
opisano detaljno u issue #77 Obrasci - ovo zanemariti (kad se već ne da obrisati)

**Comment by schlos** [comment]
Ovaj ticket se sastoji od 2 dijela:

1) Obrasci za zalbe --> duplicira: Add request templates and appeal template #9
2) Obrasci za predstavke

Pa cemo prepraviti ovaj ticket da pokriva samo predstavke.

**Comment by schlos** [comment]
Funkcionalnost slanja predstavki je dodana.

Interna prezentacija s hodogramom:
https://docs.google.com/presentation/d/e/2PACX-1vQPdl8MvgsI3--uUe-uu7JZn4zK_u4OBNgAHAecMtgpVKEi58KaYg-QTdK-eZgqyakv1KabvyKv1irh/pub?start=false&loop=false&delayms=3000

**Comment by schlos** [comment]
Related: https://github.com/mysociety/whatdotheyknow-theme/issues/17
