### ISSUE TITLE
Obrasci - help users with FOI refusals

### ISSUE THREAD

**Issue by MeliSkeli** [codeforcroatia/imamopravoznati-theme#77]
### Actual behavior
Upute za podnošenje zahtjeva i što činiti u slučaju odbijanja ili šutnje tijela trenutno su dostupne na pod-stranici "Pomoć" u rubrici "Podnošenje zahtjeva" http://imamopravoznati.org/help/requesting
Obrasci za podnošenje žalbe kao i niz drugih korisnih obrazaca na IPZ nisu dostupni, a nalaze se na stranici PristupInfo https://www.pristupinfo.hr/pravni-okvir/upute-smjernice-obrasci/ pod naslovom "Preuzimanje obrazaca"
### Steps to reproduce
Postaviti u lijevu kolonu na pod-stranicu "Podnesite zahtjev" na istom mjestu gdje na pod-stranici "Tijela javne vlasti" postoji "Prikaži samo..." linkove na sljedeće obrasce s PristupInfo uz napomenu da ih nije potrebno kopirati, ali mogu biti korisni jer sadrže obavezne elemente:
Naslov: Osnovni elementi zahtjeva:
za pristup informacijama - link: https://www.pristupinfo.hr/wp-content/uploads/2018/10/Obrazac-2-Zahtjev-za-pristup-informacijama.doc
za pristup informacijama za ponovnu uporabu - link: - Zahtjev za ponovnu uporabu https://www.pristupinfo.hr/wp-content/uploads/2018/10/Obrazac-4-Zahtjev-za-ponovnu-uporabu-informacija-1.doc
Naslove "Tražili su me da trebam ispuniti obrazac!" i "Tražili su da nadopunim zahtjev poštanskom adresom!" linkati s http://imamopravoznati.org/help/requesting
Naslov: Što ako nisam zadovoljan odgovorom:
Zahtjev za dopunu ili ispravak https://www.pristupinfo.hr/wp-content/uploads/2018/10/Obrazac-3-Zahtjev-za-dopunu-ili-ispravak-informacije-1.doc
Žalba protiv rješenja https://www.pristupinfo.hr/wp-content/uploads/2018/10/Zalba-protiv-rjesenja-pristup-informacijama.doc
Žalba protiv rješenja ponovna uporaba https://www.pristupinfo.hr/wp-content/uploads/2018/10/Zalba-protiv-rjesenja-ponovna-uporaba-informacija.doc
Žalba šutnja uprave - https://www.pristupinfo.hr/wp-content/uploads/2018/10/Zalba-protiv-rjesenja-ponovna-uporaba-informacija.doc
Žalba šutnja uprave ponovna uporaba - https://www.pristupinfo.hr/wp-content/uploads/2018/10/Zalba-sutnja-uprave-ponovna-uporaba-informacija.doc
### Expected behavior
Brže i lakše snalaženje kod podnošenja zahtjeva i upute za sljedeće korake u slučaju šutnje uprave, nedostatnog odgovora ili nezadovoljavajućeg rješenja

**Comment by schlos** [comment]
Drugi nacin rjesavanja ovog issuea je sljedeca funkcionalnost:
Add canned requests and responses for users https://github.com/codeforcroatia/imamopravoznati/issues/70 - vidjeti da li je bolje implementirati upstream (alaveteli) ili u nasoj custom temi.

**Comment by schlos** [comment]
Dio obrazaca biti ce rijesen kroz: Proširiti sadržaj stranice 'Nezadovoljni ste dobivenim odgovorom?' #71

**Comment by MeliSkeli** [comment]
Hm, ovo nisam sasvim sigurna da razumijem... možda da se čujemo oko toga kad stigneš?

**Comment by schlos** [comment]
Hehe ostavio sam sebi biljeske da ne zaboravim :)
Cujemo se za ovo zajedno s ostalim ticketima.

**Comment by schlos** [comment]
Similar to: Add request templates and appeal template #9

**Comment by schlos** [comment]
For appeal process, refer to new configuration in v0.30.0.0: https://github.com/mysociety/alaveteli/pull/3043

https://github.com/mysociety/alaveteli/blob/release/0.30.0.0/config/general.yml-example#L902

**Comment by schlos** [comment]
Duplicates: https://github.com/codeforcroatia/imamopravoznati-theme/issues/9

**Comment by schlos** [comment]
See also:
https://github.com/mysociety/alaveteli/issues/3514

See also:
https://github.com/codeforcroatia/imamopravoznati/issues/70#issuecomment-897564914

**Comment by schlos** [comment]
See this blog post how WhatDoTheyKnow are tackling with this:
https://www.mysociety.org/2021/06/25/a-tool-to-help-challenge-foi-refusals-now-on-whatdotheyknow/

**Comment by schlos** [comment]
### Copying from https://github.com/codeforcroatia/imamopravoznati/issues/70

For responses in a particular situations, see also:
https://www.mysociety.org/2021/06/25/a-tool-to-help-challenge-foi-refusals-now-on-whatdotheyknow/

Snippets functionality on WDTK (needs to be enabled via AlaveteliFeatures.backend.enable :refusal_snippets)

Help:
https://github.com/mysociety/whatdotheyknow-theme/tree/master/config/refusal_advice

Exceptions:
https://github.com/mysociety/whatdotheyknow-theme/blob/757ffa221aead059b070b591f8cb85a80080a2d2/lib/model_patches.rb#L49-L58

Edit theme:
https://github.com/mysociety/whatdotheyknow-theme/blob/549459988e9d70c1abf3d93ec75ba5e1d1fb0591/lib/views/help/unhappy.html.erb#L216

More info:
https://github.com/mysociety/alaveteli/issues/5910
https://github.com/mysociety/alaveteli/milestone/55

Alaveteli related:
https://github.com/mysociety/alaveteli/blob/0d029c6253c4b32c1aa2afe35c79de6913372369/app/views/request/_incoming_refusals.html.erb

**Comment by schlos** [comment]
From https://github.com/codeforcroatia/imamopravoznati/issues/33

Duje:

Kad se odabere status da je dobivena samo djelomična informacija – automatski generirana poruka treba biti:

„Poštovani, Sukladno članku 24. Zakona o pravu na pristup informacijama tražim nadopunu dostavljenih informacija … S poštovanjem,“

Current:
User will see "unhappy" page.

TBD:
- to add option similar to "internal_review=1#followup" for "Zahtjev za dopunu ili ispravak informacije" (maybe needs little different unhappy page similar to unhappy page)

**Comment by schlos** [comment]
From https://github.com/codeforcroatia/imamopravoznati/issues/32

Duje:
Kad se odabere status da je zahtjev u potpunosti riješen – automatski generirana poruka - odgovor tijelu javne vlasti - treba biti:

„Poštovani, Zahvaljujem na dostavi traženih informacija. S poštovanjem, “

(a ne kao sad … „temeljem zakona… tražim…“)

Sada: svaki puta za svaki odgovor je u tijelu zahtjeva i odgovora isti predlozak

**Comment by schlos** [comment]
Fixed with new "unhappy" page.

Also see: Add request templates and appeal template #9

**Comment by schlos** [comment]
Primjer:
https://translate.google.com/translate?sl=fr&tl=hr&hl=en&u=https://madada.fr/aide/cada&client=webapp
