### ISSUE TITLE
Naslovnica: Kako ovo radi?

### ISSUE THREAD

**Issue by MeliSkeli** [codeforcroatia/imamopravoznati-theme#79]
### Actual behavior
Tekst treba editirati

### Steps to reproduce
https://qsnapnet.com/snaps/sy8tocoufw

### Expected behavior
PODNASLOV: "Vaše je pravo da od tijela javne vlasti tražite rješenja, pravilnike, ugovore, izvješća, planove, odluke, statute i druge dokumente. Imamo pravo znati efikasno ukazuje na probleme koji nas okružuju i doprinosi njihovom pozitivnom rješavanju. Odgovori na zahtjeve objavljeni su i svima uvijek dostupni." 
1. KOCKA: "Pošaljete vaš zahtjev za pristup informacijama - pokazat ćemo vam kako.
2. KOCKA: "Bit ćete obavješteni e-mailom čim na vaš zahtjev stigne odgovor.
3. KOCKA: "Sada imate informacije koje ste tražili i svako im može pristupiti.

Grafički ujednačen broj znakova = atraktivniji izgled i bolja preglednost

**Comment by LanaPdg** [comment]
Editiran naslov; Način funkcioniranja portala

Editiran tekst u kockama

**Comment by schlos** [comment]
Ceka da se uploda nova verzija prijevoda na portal.

**Comment by schlos** [comment]
Izmjene uplodane na web @MeliSkeli provjeri je li sada dobro.

Ispravke mozete raditi putem Transifexa:
https://www.transifex.com/code-for-croatia/imamo-pravo-znati/theme-v03300po/
