### ISSUE TITLE
Naslovnica: rubriku "Od koga mogu tražiti informacije" zamjeniti s "Statistike o poštivanju Zakona"

### ISSUE THREAD

**Issue by MeliSkeli** [codeforcroatia/imamopravoznati-theme#81]
### Actual behavior
Top lista tijela prema broju zahtjeva

Rubrika "Od koga mogu tražiti informacije?" na naslovnoj stranici oznaceno na screenshotu:
https://qsnapnet.com/snaps/uooxv9zhr5d
![Imamo pravo znati - Napravite i pretražite zahtjeve za pristup informacijama (ZPPI)](https://user-images.githubusercontent.com/1014134/60459431-774f3e00-9c41-11e9-93db-cf7339fb0e33.jpg)

### Steps to reproduce
n/a

### Expected behavior
Informativnije i atraktivnije

Ovaj bi prostor mogli iskoristiti za preglednije statistike tipa:

- top 5 tijela prema broju zahtjeva
- top 5 tijela prema broju odgovorenih zahtjeva
- top 5 tijela prema broju odbijenih zahtjeva
- top 5 tijela koja ne odgovaraju na zahtjeve

Staviti novi naslov i podnaslov:
NASLOV: Statistike o poštivanju Zakona
PODASLOV: Među 6.314 (broj treba ažurirati) tijela javne vlasti, ova se izdvajaju u statistikama.

**Comment by schlos** [comment]
@MeliSkeli iz opisa nije jasno zelis li novu stranicu ili poboljsati postojecu?

Ovo je postojeca:
http://imamopravoznati.org/body_statistics

Mozes li pojasniti reba li samo text promijeniti?

**Comment by MeliSkeli** [comment]
Mislila sam, umjesto rubrike "Od koga mogu tražiti informacije" na naslovnici dolje lijevo staviti statistike - mogu biti grafovi, a može se staviti i popis tijela po rednim brojevima (što mi se za ovu poziciju možda čini i preglednije)

**Comment by schlos** [comment]
Dodao sam u glavni opis pod Current screenshot: https://qsnapnet.com/snaps/uooxv9zhr5d

Statistika vec postoji na odvojenoj stranici:
- http://imamopravoznati.org/body_statistics
- @MeliSkeli jesi li neke dijelove iz te statistike staviti umjesto rubrike "Od koga mogu tražiti informacije"? Ako da, mozes li nabrojati koje? Kao graf kao na toj stranici ili kao rang lista?

**Comment by MeliSkeli** [comment]
Da, ponavljam koje sam nabrojala i mislim da bi bilo preglednije da ih objavimo kao listu (u zagradi pored možemo staviti brojke)
- top 5 tijela prema broju zahtjeva
- top 5 tijela prema broju odgovorenih zahtjeva
- top 5 tijela prema broju odbijenih zahtjeva
- top 5 tijela koja ne odgovaraju na zahtjeve
Staviti novi naslov i podnaslov:
NASLOV: Statistike o poštivanju Zakona
PODASLOV: Među 6.314 (broj treba ažurirati) tijela javne vlasti, ova se izdvajaju u statistikama.

**Comment by MeliSkeli** [comment]
Da, a statistike sam gore nabrojala + mislim da bi bilo preglednije da su liste (u zagradu možemo staviti brojeve) nego grafovi

**Comment by schlos** [comment]
Zasto si ovo zatvorila @MeliSkeli ? Je li i dalje potrebno ovo ili je ispalo iz igre?

**Comment by schlos** [comment]
Vec imamo statistiku po top 10 tijela (na http://imamopravoznati.org/body_statistics) za:
- top 10 tijela s najvise zahtjeva
- top 10 tijela s najvise uspjesnih zahtjeva
- top 10 tijela s najmanje uspjesnih zahtjeva
- top 10 tijela s najvise prekoracenim rokovima za odgovor
- top 10 tijela koja su odgovorila "nemamo informacije"

Te podatke mozemo iskoristiti za ovu listu. Trebati ce developati malo, pa trebamo vanjsku pomoc.

@MeliSkeli, da li da iskoristimo top 10 ili skratimo na top 5?

**Comment by MeliSkeli** [comment]
A slučajno :-D aj pls ako ima online kakav ubrzani tečaj osnova githuba koji mi možeš preporučiti?

**Comment by MeliSkeli** [comment]
dobar prijedlog - bolje bi izgledalo da skratimo na top5

**Comment by schlos** [comment]
Offtopic disclaimer

@MeliSkeli,
ovdje je opisan project management na Githubu i alati koje Github nudi:
https://github.com/features/project-management/

ovdje imas nekoliko Github tecaja - no neki su mozda namjenjeni za programere:
https://www.udemy.com/git-started-with-github/
https://www.udemy.com/short-and-sweet-get-started-with-git-and-github-right-now/
https://hackernoon.com/top-5-free-courses-to-learn-git-and-github-best-of-lot-2f394c6533b0
https://eu.udacity.com/course/how-to-use-git-and-github--ud775

mislim da si ti mislila na project management tecaj:
https://www.youtube.com/watch?v=6fByt0o4UYs
https://www.youtube.com/watch?v=OIE_KXnSOXY

**Comment by schlos** [comment]
Note to self:
* smanjiti broj TJV koji se prikazuju na listi

Sve ostao je long term.

**Comment by schlos** [comment]
Statistics available on stats page: https://github.com/mysociety/alaveteli/blob/1255bb4599339c150d74292490b384c683dd746c/app/views/statistics/index.html.erb

**Comment by schlos** [comment]
Pseudo-kod za "od koga mogu traziti informacije" - da ne pokazuje listu vec statistiku:

**_Note to self_**

Work in https://github.com/codeforcroatia/imamopravoznati-theme/blob/imamopravoznati-0.33.0.0/lib/views/general/_frontpage_bodies_list.html.erb

This didn't work:

```
<ul>
<% @public_bodies.each do |graph_data| %>
  <strong><%= graph_data['title']%></strong>
  <% if graph_data['x_values'] %>
    <li><%= link_to pb['name'], pb['url'] %>
      <%= n_('{{count}} request', '{{count}} requests',
             graph_data['y_values'][i].round,
             :count => graph_data['y_values'][i].round) %>
    </li>
  <% else %>
    <%= _("There was no data for this statistics yet.") %>
  <% end %>
<% end %>
</ul>
```


This didnt work (exact code from stats page):

```
<% @public_bodies.each do |graph_data| %>
    <h3 class="public-body-ranking-title"><%= graph_data['title']%></h3>
    <div class="public-body-ranking" id="<%= graph_data['id'] %>">
      <% if graph_data['x_values'] %>
        <table border=0>
          <thead>
            <tr>
              <th><%= _('Public Body') %></th>
              <th><%= graph_data['y_axis'] %></th>
            </tr>
          </thead>
          <tbody>
            <% graph_data['public_bodies'].each_with_index do |pb, i| %>
              <tr>
                <td><%= link_to pb['name'], pb['url'] %></td>
                <td class="statistic"><%= graph_data['y_values'][i].round %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <%= _("There was no data calculated for this graph yet.") %>
      <% end %>
    </div>
  <% end %>
```

**Comment by schlos** [comment]
Ideja za statistiku na homepageu:
https://github.com/n-mouse/askgovge-theme/blob/design-2/lib/views/general/_frontpage_hero.html.erb

Screenshot:
https://app.snippyly.com/discuss/?q=v98YrPZBvwgXOF0vycAC
