### ISSUE TITLE
Naslovnica: Koje su informacije objavljene

### ISSUE THREAD

**Issue by MeliSkeli** [codeforcroatia/imamopravoznati-theme#82]
### Actual behavior
Prikazuje posljednje pristigle odgovore
Screenshot: https://qsnapnet.com/snaps/peynu6s1mk

### Steps to reproduce
1.
2.
3.

### Expected behavior
Promijeniti naslov i podnaslov:
NASLOV: Posljednje objavljene informacije
PODNASLOV: Pretražiti možete svih 6.798 zahtjeva koje su podnijeli korisnici, a najnoviji su: 

jasniji opis sadržaja = atraktivniji izgled

**Comment by schlos** [comment]
Ispravljeno na Trasifexu. Ceka da se uploda nova verzija prijevoda na portal.

**Comment by schlos** [comment]
Izmjene uplodane na web @MeliSkeli provjeri je li sada dobro. Meni izgleda da i dalje nije dobar text.

Ispravke mozete raditi putem Transifexa:
https://www.transifex.com/code-for-croatia/imamo-pravo-znati/theme-v03300po/

**Comment by MeliSkeli** [comment]
Nisam ulogirana u Transifex pa evo par sitnica sam na naslovnici označila na .png u att

**Comment by MelisaS** [comment]
![Izrezak](https://user-images.githubusercontent.com/32191788/69498590-baa89280-0ee9-11ea-91c2-c6ad97e2c66b.PNG)

**Comment by LanaPdg** [comment]
Dobijte - tražite                                --- ispravljeno na transifexu (theme)
Registrirajte se - se registrirajte       --- ispravljeno na transifexu (app)
Želite znati nešto? - Imate pitanje? --- ispravljeno na transifexu (app)
UK - Hrvatskoj                                 --- ispravljeno na transifexu (theme)

**Comment by schlos** [comment]
Pseudo-kod za "od koga mogu traziti informacije" - da ne pokazuje listu vec statistiku:

**_Note to self_**

Work in https://github.com/codeforcroatia/imamopravoznati-theme/blob/imamopravoznati-0.33.0.0/lib/views/general/_frontpage_bodies_list.html.erb

This didn't work:

```
<ul>
<% @public_bodies.each do |graph_data| %>
  <strong><%= graph_data['title']%></strong>
  <% if graph_data['x_values'] %>
    <li><%= link_to pb['name'], pb['url'] %>
      <%= n_('{{count}} request', '{{count}} requests',
             graph_data['y_values'][i].round,
             :count => graph_data['y_values'][i].round) %>
    </li>
  <% else %>
    <%= _("There was no data for this statistics yet.") %>
  <% end %>
<% end %>
</ul>
```


This didnt work (exact code from stats page):

```
<% @public_bodies.each do |graph_data| %>
    <h3 class="public-body-ranking-title"><%= graph_data['title']%></h3>
    <div class="public-body-ranking" id="<%= graph_data['id'] %>">
      <% if graph_data['x_values'] %>
        <table border=0>
          <thead>
            <tr>
              <th><%= _('Public Body') %></th>
              <th><%= graph_data['y_axis'] %></th>
            </tr>
          </thead>
          <tbody>
            <% graph_data['public_bodies'].each_with_index do |pb, i| %>
              <tr>
                <td><%= link_to pb['name'], pb['url'] %></td>
                <td class="statistic"><%= graph_data['y_values'][i].round %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <%= _("There was no data calculated for this graph yet.") %>
      <% end %>
    </div>
  <% end %>
```

**Comment by schlos** [comment]
Code part fixed with 0.38.0.0 or earlier; Transifex can still be updated if there are open issues.
