### ISSUE TITLE
Translate "publication scheme" - dodatne informacije o PPI ovog tijela javne vlasti

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati-theme#87]
### Expected behavior

Dodati u prijevode “publication scheme” kao url do stranice s PPI informacijama (prije: katalog informacija)

Za vise info procitati:
https://ico.org.uk/for-organisations/guide-to-freedom-of-information/publication-scheme/

**Comment by LanaPdg** [comment]
@schlos please check; https://www.transifex.com/code-for-croatia/imamo-pravo-znati/translate/#hr/app-v03300po/184521761?q=text%3Ascheme

**Comment by schlos** [comment]
Izmjene uplodane na web @LanaPdg hoces lu provjeriti je li sada dobro?

Nove ispravke mozes raditi putem Transifexa:
https://www.transifex.com/code-for-croatia/imamo-pravo-znati/

**Comment by LanaPdg** [comment]
Promijenjeno u  Stranice sa PPI informacijama
