### ISSUE TITLE
Translate "disclosure log" - katalog odgovora

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati-theme#88]
### Expected behavior

Disclosure log je katalog odgovora.

Vise informacija:
* https://www.foiman.com/resources/foiguide1

**Comment by LanaPdg** [comment]
@schlos please check; https://www.transifex.com/code-for-croatia/imamo-pravo-znati/translate/#hr/app-v03300po/184521761?q=text%3Ascheme

[#664]

**Comment by schlos** [comment]
Izmjene uplodane na web @LanaPdg hoces lu provjeriti je li sada dobro?

Nove ispravke mozes raditi putem Transifexa:
https://www.transifex.com/code-for-croatia/imamo-pravo-znati/

**Comment by LanaPdg** [comment]
@schlos promijenjeno u Ostvarivanje prava na pristup informacijama
